apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy
  labels:
    app: udagram-reverseproxy
spec:
  selector:
    matchLabels:
      app: udagram-reverseproxy
  replicas: 2
  template:
    metadata:
      labels:
        app: udagram-reverseproxy
    spec:
      containers:
        - name: udagram-reverseproxy
          image: medchakhman/udacity_udagram_reverseproxy:v1.0.0
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USERNAME
              value: postgres
            - name: POSTGRES_PASSWORD
              value: mazal159630
            - name: POSTGRES_HOST
              value: database-1.cdlieqo3tsoh.us-east-2.rds.amazonaws.com
            - name: AWS_BUCKET
              value: arn:aws:s3:::monolith-to-mc
            - name: AWS_REGION
              value: us-east-2
            - name: AWS_PROFILE
              value: default
            - name: JWT_SECRET
              value: testing
            - name: URL
              value: http://localhost:8100
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
